spring.application.name=najvecaLolcina

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=root

spring.security.user.name=user
spring.security.user.password=user

jwt.secret=g5U7S1m+o0fP8VQK7c9JmT3mL8dA2L4yV1zX0Q9R6sE=

spring.jpa.hibernate.ddl-auto=update



